### PR TITLE
Added Stylus Mixin

### PR DESCRIPTION
**Pull request by tiagoporto**
To support the largest CSS pre-processors, I added the mixin for the Stylus.

### CODE REVIEW

**Comment by Lori1072** [comment]
How can I fix this,? WHy is there new issues?

**Comment by tiagoporto** [comment]
@Lori1072 This isn't a Issue. This is a pull request with the insertion of stylus mixin.

**Comment by Lori1072** [comment]
ok thank You....I appreciate. A question I am trying to make website quicker,, WHat can I do as Far as compresssion..

**Comment by joshuaiz** [comment]
@Lori1072, these are issues specifically related to retina.js and not the appropriate place for your questions. You apparently are watching this repository so you will get all the messages that are posted - some are issues, some are pull or merge requests. 

There are tons of resources available online with information on speeding up your site but this is not the place to go for support for this.

**Pull request closed without merging**
